from pydantic import BaseModel, Field


class EntityMapEntry(BaseModel):
    entity_id: str = Field(
        description=(
            "Unique identifier generated by the AI for a distinct physical "
            "entity identified in the Overview Images. The same physical "
            "entity must keep the same ID across all Overview Images."
        )
    )
    entity_type: str = Field(
        description=(
            "The domain entity type of the identified entity. Must correspond "
            "to an entity type provided in the Entity Scope, such as Wall, "
            "Floor, Door, Window, BuildingElement, or RoomObject."
        )
    )
    owner_entity_id: str = Field(
        description=(
            "Identifier of the parent entity to which this entity initially "
            "belongs. A Wall belongs to the Room, Door and Window entities "
            "belong to their Wall, and RoomObject entities belong to the Room."
        )
    )
    spatial_context: str | None = Field(
        default=None,
        description=(
            "Coarse free-text description of the entity's spatial position "
            "or context within the room; not a formal relationship model."
        ),
    )
    visible_in: list[str] = Field(
        description=(
            "IDs of the Overview Images in which this same physical entity is "
            "visibly present."
        )
    )


class InitialEntitySpatialMap(BaseModel):
    entities: list[EntityMapEntry] = Field(
        description=(
            "All distinct relevant physical entities identified across the "
            "Overview Images, consolidated across multiple views."
        )
    )
